export type FastIntent = {
  keys: string[];
  reply: string;
};

export const FAST_INTENTS: FastIntent[] = [
  { keys: ["warm light", "warm lights"], reply: "Got it. Warm lights on now." },
  { keys: ["cool light", "cold light"], reply: "Switching to cool lights now." },
  // { keys: ["ambient light", "ambient mode"], reply: "Ambient lighting enabled." },
  // { keys: ["dim lights", "lower lights", "lower the lights"], reply: "Dimming the lights for you." },
  // { keys: ["brighten lights", "brighter lights"], reply: "Brightening the lights now." },
  // { keys: ["raise temperature", "warmer", "increase temp", "hotter"], reply: "Raising temperature to comfort mode." },
  // { keys: ["lower temperature", "cooler", "decrease temp", "colder"], reply: "Lowering temperature now." },
  // { keys: ["cold", "freezing", "chilly", "i'm cold"], reply: "Warming up the room for you." },
  // { keys: ["hot", "boiling", "sweating", "too hot"], reply: "Cooling down the room for you." },
  // { keys: ["temperature", "degrees"], reply: "Adjusting the thermostat to your preferred level." },
  // { keys: ["turn off lights", "lights off"], reply: "Lights off now." },
  // { keys: ["turn on lights", "lights on"], reply: "Lights on to standard level." },
  // { keys: ["relax mode", "rest mode"], reply: "Relax mode on: soft lights and steady climate." },
  // { keys: ["open curtains", "raise blinds"], reply: "Opening curtains now." },
  // { keys: ["close curtains", "lower blinds"], reply: "Closing curtains now." },
  // { keys: ["towels"], reply: "Towels requested. Staff notified." },
  // { keys: ["pillows", "extra pillow"], reply: "Extra pillows are on the way." },
  // { keys: ["water", "bottle of water"], reply: "Sending water to your room." },
  // { keys: ["cleaning", "housekeeping"], reply: "Housekeeping requested." },
  // { keys: ["room service"], reply: "Room service notified immediately." },
  // { keys: ["wake up", "alarm"], reply: "Wake-up call scheduled." },
  // { keys: ["taxi", "uber", "ride"], reply: "Arranging a ride for you now." },
  // { keys: ["spa", "massage"], reply: "Scheduling a spa option for you." },
  // { keys: ["checkout", "check out"], reply: "Starting secure checkout now." },
  // { keys: ["late checkout", "late check out"], reply: "Late checkout requested." },
  // { keys: ["do not disturb", "dnd"], reply: "Do Not Disturb is now on." },
  // { keys: ["tv on", "turn on tv", "turn on the tv"], reply: "Turning on the TV. Anything specific you'd like to watch?" },
  // { keys: ["tv off", "turn off tv", "turn off the tv"], reply: "TV is now off." },
  // { keys: ["wifi", "wi-fi", "internet password"], reply: "Wi-Fi is ORIN_GUEST. No password required for verified accounts." },
  // { keys: ["breakfast", "dining", "food hours"], reply: "Breakfast is served in the lobby from 7 AM to 10 AM." },
  // { keys: ["gym", "fitness", "pool", "swimming"], reply: "The fitness center and pool are on the 2nd floor, open 24/7." },
  // { keys: ["luggage", "bags", "bellhop"], reply: "A bellhop will be at your door shortly to assist with your luggage." },
  // { keys: ["front desk", "reception", "call help"], reply: "Connecting you to the front desk now." },
  // { keys: ["ac on", "turn on ac", "air conditioning"], reply: "Air conditioning is now on and set to your preferred level." },
  // { keys: ["ac off", "turn off ac"], reply: "Air conditioning turned off." },
  // { keys: ["laundry", "dry cleaning", "ironing"], reply: "Laundry services are available daily. Please place items in the bag provided." },
  // { keys: ["coffee", "tea", "minibar"], reply: "Restocking your minibar and coffee station now." },
  // { keys: ["reading light", "bedside light"], reply: "Reading light on. Enjoy your book." },
  // { keys: ["night light", "soft light"], reply: "Night light enabled for your comfort." },
  // { keys: ["weather", "outside"], reply: "It's currently 22 degrees and sunny. Perfect day to explore!" },
  // { keys: ["emergency", "help"], reply: "Emergency services notified. Stay where you are, help is coming." },
  // { keys: ["thank you", "thanks"], reply: "You're very welcome! I'm here to help." },
  // { keys: ["good morning"], reply: "Good morning! I hope you slept well. How can I assist you today?" },
  // { keys: ["good night"], reply: "Good night! I've set the room to your sleep preferences. Rest well." },
];
